version: '3.8'
services:
  # Frontend (Vue.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend
    networks:
      - app-network

  # Backend (PHP con Apache)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=sail
      - DB_PASSWORD=password
      - FRONTEND_URL=http://localhost:3000
      - SSL_ENABLED=true
    depends_on:
      - mysql
    networks:
      - app-network
    restart: unless-stopped

  # Base de datos MySQL
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=sail
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped

  # phpMyAdmin para gestión de base de datos
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - UPLOAD_LIMIT=300M
      - PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD=password
    depends_on:
      - mysql
    networks:
      - app-network
    restart: unless-stopped

  # Redis (para caché, sesiones, etc.)
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data: 